name: 'Reusable Workflow: Documentation'

on:
  workflow_call:
    inputs:
      pacEnvironmentSelector:
        required: true
        type: string
      planGitHubEnvironment:
        required: true
        type: string
      PAC_OUTPUT_FOLDER:
        required: true
        type: string
      PAC_DEFINITIONS_FOLDER:
        required: true
        type: string
    outputs:
      documentation:
        description: "The result of evaluating if a policy deployment is required"
        value: ${{ jobs.plan.outputs.documentation }}

env:
  PAC_OUTPUT_FOLDER: ./Output
  PAC_DEFINITIONS_FOLDER: ./Definitions

jobs:
  document:
    runs-on: ubuntu-latest
    environment: ${{ inputs.planGitHubEnvironment }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Required Modules
        uses: Azure/powershell@v2
        with:
          inlineScript: |
            Install-Module EnterprisePolicyAsCode -Force
          azPSVersion: "latest"

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          enable-AzPSSession: true
          allow-no-subscriptions: true

      - name: Documentation
        uses: azure/powershell@v2
        with:
          inlineScript: 'Scripts/Operations/Build-PolicyDocumentation.ps1 -PacEnvironmentSelector ${{ inputs.pacEnvironmentSelector }} -InformationAction Continue'
          azPSVersion: "latest"

      - name: Upload Deployment Plan as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: "documentation"
          path: ${{ env.PAC_OUTPUT_FOLDER }}
          if-no-files-found: error
